# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - 6969:5432
    environment:
      POSTGRES_PASSWORD: bjjarmbar
    