# Use postgres/example user/password credentials
version: '3'

services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - 6969:5432
    environment:
      POSTGRES_PASSWORD: bjjarmbar
  app:
    image: python:3.6-slim
    build: .
    depends_on:
      - db
    container_name: app
    